# Reshape

In [1]:
import numpy as np

In [5]:
a=np.array([11,22,33,44])
at=a.reshape(2,2)
at

array([[11, 22],
       [33, 44]])

In [6]:
b=np.array([1,2,3,4,5,6,7,8,9])
at=b.reshape(9,1)
at

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
c=np.array([96,45,75,32,10,20])
at=c.reshape(3,2)
at

array([[96, 45],
       [75, 32],
       [10, 20]])

In [11]:
d=np.array([98,97,96,95,94,93,92,91,90,89,88])
at=d.reshape(1,11)
at

array([[98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88]])

In [12]:
d=np.array([98,97,96,95,94,93,92,91,90,89,88])
at=d.reshape(11,1)
at

array([[98],
       [97],
       [96],
       [95],
       [94],
       [93],
       [92],
       [91],
       [90],
       [89],
       [88]])

In [15]:
ab=np.array([4,5,6,2])
at=ab.reshape(2,2)
at

array([[4, 5],
       [6, 2]])

In [16]:
ab=np.array([963,456,123,785,963,521,183])
at=ab.reshape(7,1)
at

array([[963],
       [456],
       [123],
       [785],
       [963],
       [521],
       [183]])

In [17]:
ab=np.array([1,2,3,5,5,6,7,8,9,10])
at=ab.reshape(5,2)
at

array([[ 1,  2],
       [ 3,  5],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
ab=np.array([1,2,3,5,5,6,7,8,9,10])
at=ab.reshape(5,2)
at