In [7]:
import numpy as np

In [8]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [9]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
a=np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [11]:
a=np.array([[1,2],[3,4]])
print(a.ndim)

2


In [20]:
a=np.array([[1,2],[3,4]])
print(a.dtype)

int32


In [19]:
a1=np.array([1,2,5,4,56])
print(a1.dtype)

int32


In [24]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [25]:
a=np.array(5)
print(a.ndim)

0


In [41]:
a=np.array(6)
print(a.ndim)

0


In [47]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [44]:
a=np.array([[[[11,12,13,14],[12,16,17,18],[19,20,21,22],[23,24,25,26],]]])
print(a)

[[[[11 12 13 14]
   [12 16 17 18]
   [19 20 21 22]
   [23 24 25 26]]]]


In [48]:
ap=np.array([[[[[82,53,26,47],[45,52,46,55]]]]])
print(ap)

[[[[[82 53 26 47]
    [45 52 46 55]]]]]


In [49]:
ap=np.array([[[[[82,53,26,47],[45,52,46,55]]]]])
print(ap.dtype)

int32


In [63]:
ap=np.array([[[[82,53,26,47],[45,52,46,55]]]])
print(ap.shape)

(1, 1, 2, 4)


In [51]:
ap=np.array([[[[[82,53,26,47],[45,52,46,55]]]]])
print(ap.ndim)

5


In [56]:
ap=np.array([[[[[82,53,26,47],[45,52,46,55],[41,22,64,66],[47,54,63,12]]]]])
print(ap)

[[[[[82 53 26 47]
    [45 52 46 55]
    [41 22 64 66]
    [47 54 63 12]]]]]


In [1]:
#concatenate

In [5]:
import numpy as np
a1 = np.array([12,34,45,67,89,13])
a2 = np.array([76,67,34,87,34,12])

at = np.concatenate((a1,a2))
print(at)

[12 34 45 67 89 13 76 67 34 87 34 12]


In [6]:
import numpy as np
a1 = np.array([12,34,45,67,89,13])
a2 = np.array([76,67,34,87,34,12])
a3 = np.array([45,67,89])

at = np.concatenate((a1,a2,a3))
print(at)

[12 34 45 67 89 13 76 67 34 87 34 12 45 67 89]


In [7]:
a1 = np.array([12,34,45,67,89,13])

at = np.array(a1[0]+a1[2])
print(at)

57


In [8]:
a1 = np.array([12,34,45,67,89,13])
a2 = np.array([76,67,34,87,34,12])
a3 = np.array([45,67,89])

at = np.array(a1[2]*a3[2]+a2[1])
print(at)

4072


# reshape


In [1]:
import numpy as np

In [2]:
a1 = np.array([12,23,34,45,56,67,67,78,45])
at = a1.reshape(1,9)
at

array([[12, 23, 34, 45, 56, 67, 67, 78, 45]])

In [4]:
a=np.array([1,2,3,4])
b=a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [3]:
a1 = np.array([12,23,34,45,56,67,67,78,45])
at = a1.reshape(9,1)
at

array([[12],
       [23],
       [34],
       [45],
       [56],
       [67],
       [67],
       [78],
       [45]])

In [11]:
a2 = np.array([1,2,3,4,5,6])
at = a2.reshape([3,2])
at

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a2 = np.array([1,2,3,4,5,6])
at = a2.reshape([2,3])
at

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3 = np.array([1,2,3,4,5,6,7,8,9,11])
at = a3.reshape([1,10])
at

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [16]:
a3 = np.array([1,2,3,4,5,6,7,8,9,11])
at = a3.reshape([2,5])
at

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [17]:
a3 = np.array([1,2,3,4,5,6,7,8,9,11])
at = a3.reshape([5,2])
at

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

# split

In [21]:
aa1 = np.array([1,2,3])
at = np.array_split(aa1,2)
at

[array([1, 2]), array([3])]

In [13]:
a=np.array([45,96,64,72])
b=np.array_split(a,4)
b

[array([45]), array([96]), array([64]), array([72])]

In [26]:
aa2 = np.array([23,34,45,56,67,78,89,12])
at = np.array_split(aa2,4)
at

[array([23, 34]), array([45, 56]), array([67, 78]), array([89, 12])]

In [28]:
aa2 = np.array([23,34,45,56,67,78,89,12])
at = np.array_split(aa2,10)
at

[array([23]),
 array([34]),
 array([45]),
 array([56]),
 array([67]),
 array([78]),
 array([89]),
 array([12]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [38]:
aa3 = np.array([[1,2,3],[4,5,6],[5,6,7]])
at = np.array_split(aa3,3)
at

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[5, 6, 7]])]

In [40]:
a1 = np.array([4,5,6,7,8,9])
at = np.array_split(a1,3)
at

[array([4, 5]), array([6, 7]), array([8, 9])]

In [43]:
a2=np.array([7,6,3,4,9,2,8])
at=np.array_split(a2,6)
at

[array([7, 6]), array([3]), array([4]), array([9]), array([2]), array([8])]