# Numpy:

In [15]:
import numpy as np

In [23]:
# ndim,shape,datatype

In [24]:
a=np.array(1)
print(a.ndim)

0


In [25]:
a1=np.array([1,2])
print(a1.ndim)

1


In [26]:
a2=np.array([1,2,3,4])
print(a2.ndim)

1


In [27]:
a3=np.array([[50,60]])
print(a3.ndim)

2


In [28]:
b=np.array([11,22,33,44])
print(b.shape)

(4,)


In [29]:
b1=np.array([[111,121],[222,236]])
print(b1.shape)
print(b1.ndim)
print(b1.dtype)

(2, 2)
2
int32


In [22]:
b2=np.array([[[14,52],[25,88],[66,55]]])
print(b2.ndim)
print(b2.shape)
print(b2.dtype)

3
(1, 3, 2)
int32


In [30]:
# concatenate

In [33]:
aa=np.array([1,2,3,4,5,6])
bb=np.array([7,8,9,4,5,2])
at=np.concatenate((aa,bb))
print(at)

[1 2 3 4 5 6 7 8 9 4 5 2]


In [36]:
a12=np.array([85,45])
a23=np.array([82,63])
at=np.concatenate((a12,a23))
print(at)

[85 45 82 63]


In [39]:
x=np.array([52,55,99,72])
at=np.array(x[1]+x[3])
print(at)


127


In [40]:
x=np.array([52,55,99,72])
y=np.array([50,60,40,70])
z=np.array([42,90,33,10])
at=np.array(x[0]+y[2]+z[3])
print(at)

102


In [41]:
# reshape

In [44]:
a1 = np.array([12,23,34,45,56,67,67,78,45])
at=a1.reshape(9,1)
at

array([[12],
       [23],
       [34],
       [45],
       [56],
       [67],
       [67],
       [78],
       [45]])

In [45]:
a1 = np.array([12,23,34,45,56,67,67,78,45])
at=a1.reshape(1,9)
at

array([[12, 23, 34, 45, 56, 67, 67, 78, 45]])

In [46]:
a3 = np.array([1,2,3,4,5,6,7,8,9,11])
at = a3.reshape([5,2])
at

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11]])

In [47]:
a3 = np.array([1,2,3,4,5,6,7,8,9,11])
at = a3.reshape([2,5])
at

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [48]:
# split

In [50]:
z=np.array([8,4,3])
at=np.array_split(z,2)
at

[array([8, 4]), array([3])]

In [52]:
z=np.array([8,4,3])
at=np.array_split(z,4)
at

[array([8]), array([4]), array([3]), array([], dtype=int32)]

In [53]:
z=np.array([8,4,3])
at=np.array_split(z,1)
at

[array([8, 4, 3])]

In [54]:
z=np.array([8,4,3])
at=np.array_split(z,2)
at

[array([8, 4]), array([3])]

In [55]:
# where

In [58]:
p = np.array([1,3,5,6,7,2,4,8])
at=np.where(p==6)
at


(array([3], dtype=int64),)

In [59]:
p = np.array([1,3,5,6,7,2,4,8])
at=np.where(p==8)
at

(array([7], dtype=int64),)

In [60]:
xy=np.array([[52,45,20],[72,93,92],[10,50,90]])
at=np.where(xy==10)
at

(array([2], dtype=int64), array([0], dtype=int64))

In [61]:
xy=np.array([[52,45,20],[72,93,92],[10,50,90]])
at=np.where(xy==92)
at

(array([1], dtype=int64), array([2], dtype=int64))

In [62]:
# sort

In [69]:
#ascending

In [70]:
a=np.array([100,47,60,50,2,80])
np.sort(a)

array([  2,  47,  50,  60,  80, 100])

In [71]:
ab=np.array([[824,93,456,420],[786,200,600,450]])
np.sort(ab)

array([[ 93, 420, 456, 824],
       [200, 450, 600, 786]])

In [72]:
#descending

In [73]:
a=np.array([100,47,60,50,2,80])
np.sort(a)[::-1]

array([100,  80,  60,  50,  47,   2])

In [78]:
ab=np.array([[824,93,456,420],[786,200,600,450]])
-np.sort(-ab)[::-1]

array([[786, 600, 450, 200],
       [824, 456, 420,  93]])

In [79]:
ar3 = np.array([[[3,5,2,7,1],[43,78,12,0,4]],[[43,67,21,10,9],[34,90,100,2,50]]])
-np.sort(-ar3)[::-1]

array([[[ 67,  43,  21,  10,   9],
        [100,  90,  50,  34,   2]],

       [[  7,   5,   3,   2,   1],
        [ 78,  43,  12,   4,   0]]])