# Split 

In [5]:
import numpy as np

In [8]:
aa1 = np.array([1,2,3])
at = np.array_split(aa1,2)
at

[array([1, 2]), array([3])]

In [12]:
aa3 = np.array([[1,2,3],[4,5,6],[5,6,7]])
at = np.array_split(aa3,3)
at

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[5, 6, 7]])]

In [14]:
a=np.array([[11,12,13],[14,15,16]])
at=np.array_split(a,4)
at

[array([[11, 12, 13]]),
 array([[14, 15, 16]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [15]:
a=np.array([45,82,96,73,65,45,55])
at=np.array_split(a,4)
at

[array([45, 82]), array([96, 73]), array([65, 45]), array([55])]

In [23]:
a=np.array([[44,55,66],[11,22,33],[77,88,99]])
at=np.array_split(a,3)
at

[array([[44, 55, 66]]), array([[11, 22, 33]]), array([[77, 88, 99]])]

In [25]:
a=np.array([7,9,1,6,2,4,5])
at=np.array_split(a,5)
at

[array([7, 9]), array([1, 6]), array([2]), array([4]), array([5])]

In [28]:
a=np.array([7,9,1,6,2,4,5])
at=np.array_split(a,7)
at

[array([7]),
 array([9]),
 array([1]),
 array([6]),
 array([2]),
 array([4]),
 array([5])]

In [ ]:
a=np.array([[41,42,43,44],[45,46,47,48],[49,50,51,52]])
a